### PR TITLE
new prefixes

### PR DESCRIPTION
**Pull request by bernardyn**

### CODE REVIEW

**Comment by bernardyn** [comment]
Task linked: [LHDB-875 Dostosowanie ontologii do nowych prefixów](https://app.clickup.com/t/2591891/LHDB-875)

**Review by bszady — DISMISSED** [review]
Ok

**Review by przemekgradzki — APPROVED** [review]
OK after commit e177644c55ca56884f375d7fdc9d0417b8c2aedc

**Review by bszady — APPROVED** [review]

**Comment by bernardyn** [comment]
Good point. I forgot about the subclasses.

**Pull request merged**
